blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/frontend-starter/frontend-starter-cli/discussions
    about: Questions and ideas are welcome in Discussions.
