blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/mohammadhossein-asadi/frontend-starter-cli/discussions
    about: Questions and ideas are welcome in Discussions.
